<a href="https://colab.research.google.com/github/sridharkonda628/python_for_data_science/blob/main/Day03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[1,2,3,4]
squares=[]
for i in list1:
  squares.append(i*i)
print(squares)

[1, 4, 9, 16]


In [ ]:
squares2=list(map(lambda i:i*i,list1))
print(squares2)

[1, 4, 9, 16]


In [ ]:
squares2=list(filter(lambda i:i%2==0,list1))
print(squares2)

[2, 4]


In [ ]:
import numpy as ny

In [ ]:
np1=ny.array([1,2,3,6,7])
print(np1)
print(type(np1))

[1 2 3 6 7]
<class 'numpy.ndarray'>


In [ ]:
np2=ny.array([[1,2,3],[4,5,6]])
print(np2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#numpy is mutable
np1[2]=56
print(np1)

[ 1  2 56  6  7]


In [ ]:
#accesing 2D array
print(np2[0][1])

2


In [ ]:
print(len(np1),len(np2))

5 2


In [ ]:
import time
list1=[i for i in range(10**6)]
np3=ny.array(list1)

time_list=time.time()
for in list1
time_list=time.time()


time_list=time.time()

time_list=time.time()

In [ ]:
random1=ny.ones((3,3),dtype='int')
print(random1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
random2=ny.full((3,3),"")
print(random2)

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [ ]:
def check_win(board,user_value):
  #check for rows
  for i in range(0,3):
    if(ny.all(ny.(board[i])==user_value) or ny.all(board[:i]==user_value):
      return True
    if(ny.all(ny.diag(board)==user_value)):
      return True
     return False



In [ ]:
def game_start():
  board=ny.full((3,3)," ")
  player1=input("Enter your name player1")
  player1=input("Enter your name player2")
  check=player1
  while True:
    if check==player1:
      print(player1,"It's your chance now")
    else:
      print(player2,"It's your turn now!!")
  row=int(input("Enter row"))
  col=int(input("Enter col"))
  if board[row][col]!=" ":
    print("It's already occupied")
    continue
  if check==player1:
    board[row][col]='X'
    if(check_win(board,'X')):
      print(board)
      print(player1,"You won!!")
      break
  else:
    board[row][col]='X'
    if(check_win(board,'X')):
      print(board)
      print(player2,"You won!!")
      break
   if check==player1:
    check=player1
   else:
    check=player2



In [ ]:
print("Welcome TIC-TAC-TOE")
play1=input("Are you ready to start?")
if(play1=="yes!")

In [ ]:
import numpy as ny
def check_win(board,user_value):
  #check for rows
  for i in range(0,3):
    if(ny.all(board[i])==user_value) or ny.all(board[:i]==user_value):
      return True
    if(ny.all(ny.diag(board)==user_value)):
      return True
     return False
def game_start():
  board=ny.full((3,3)," ")
  player1=input("Enter your name player1")
  player1=input("Enter your name player2")
  check=player1
  while True:
    if check==player1:
      print(player1,"It's your chance now")
    else:
      print(player2,"It's your turn now!!")
  row=int(input("Enter row"))
  col=int(input("Enter col"))
  if board[row][col]!=" ":
    print("It's already occupied")
    continue
  if check==player1:
    board[row][col]='X'
    if(check_win(board,'X')):
      print(board)
      print(player1,"You won!!")
      break
  else:
    board[row][col]='X'
    if(check_win(board,'X')):
      print(board)
      print(player2,"You won!!")
      break
   if check==player1:
    check=player1
   else:
    check=player2
print("Welcome TIC-TAC-TOE")
play1=input("Are you ready to start?")
if(play1=="yes!")
  game_starts()
else:
  print("You choose not to play:(")


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [ ]:
n1=float(input("Enter 1: "))
n2=float(input("Enter 2: "))
ny.add(n1,n2)

Enter 1: 10
Enter 2: 20


30.0

In [ ]:
np2=np1
np3=np1.copy()
print(np3)

[ 1  2 56  6  7]


In [ ]:
np3[1]=85
print(np3)

[ 1 85 56  6  7]


In [ ]:
#mean
ny.mean(np1)
print(np1)

[ 1  2 56  6  7]
